name: Basic deploy
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
          key_path: '/home/xuxa/.ssh/movie-catalog-ssh-rsa.pem'
          port: ${{ secrets.PORT }}
          source: '.'
          target: '/home/ubuntu/movie-catalog-api'
