name: Basic deploy
on:
  push:
    branches: [main]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'EC2'
      url: 'ec2-3-15-33-141.us-east-2.compute.amazonaws.com'
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-2
          aws_elb_app_port: 3000 # This should match the docker exposed port. Defaults to 3000.
